CR: 0.6
F: 0.8
N_max: 32
N_min: 16
active: true
add_pure_new: false
chromosome_size: 100
crossover: true
differential_evolution: false
e: 2
elitism: false
invasive_weed: false
iter_max: 1000
lamarck_random_sequence: false
max_fitness_eval: null
max_iteration: 8000
memetic: false
min_fitness: null
mutation: true
mutation_probability: 0.2
mutation_random_sequence: false
mutation_type: basic
num_of_clones: 1
num_of_crossover: null
num_of_new_individual: 10
number_of_steps: 1
patience: null
pool: false
pool_size: 4
population_size: 100
selection_type: better half
sigma_fin: 0.05
sigma_init: 0.2
step_size: 0.1
stop: true
