population_size: 10
chromosome_size: 2000 # 43200
max_iteration: 100
max_fitness_eval:
patience:
mutation_probability: 0.2
pool_size: 4
lamarck: False
pool: False
num_of_new_individual:
num_of_crossover:
elitism: True
mutation_random: True