active: False

####### Population and other
population_size: 1000
chromosome_size: 100
pool: False
# default: cpu_count()
pool_size: 4

####### Stop conditions
max_iteration: 1000
max_fitness_eval:
min_fitness:
patience:
stop: False

############## Add new individuals methods

####### Crossover selection
crossover: False
# options: random, tournament, better half
selection_type: "random"
# default: population_size // 4
num_of_crossover:

####### Differential evolution
differential_evolution: True
# [0, 1]
CR: 0.6
# [0, 2]
F: 0.8

####### Invasive weed
invasive_weed: False

####### Add pure new individuals
add_pure_new: False
# default: population_size // 2
num_of_new_individual:

############## Modify all individulas methods

####### Mutation
mutation: True
# options: basic, bacterial
mutation_type: "basic"
elitism: True
mutation_random_sequence: True
# basic
mutation_probability: 0.2
# bacterial
num_of_clones: 1

####### Memetic
memetic: False
lamarck_random_sequence: True
step_size: 0.1
number_of_steps: 1
