active: True

####### Population and other
population_size: 100
chromosome_size: 100
pool: False
# default: cpu_count()
pool_size: 4

####### Stop conditions
max_iteration: 8000
max_fitness_eval:
min_fitness:
patience:
stop: True

############## Add new individuals methods

####### Crossover selection
crossover: False
# options: random, tournament, better half
selection_type: "random"
# default: population_size // 4
num_of_crossover:

####### Differential evolution
differential_evolution: False
# [0, 1]
CR: 0.6
# [0, 2]
F: 0.8

####### Invasive weed
invasive_weed: True
iter_max: 1000
e: 2
sigma_init: 0.2
sigma_fin: 0.05
N_min: 16
N_max: 32


####### Add pure new individuals
add_pure_new: True
# default: population_size // 2
num_of_new_individual: 10

############## Modify all individulas methods

####### Mutation
mutation: True
# options: basic, bacterial
mutation_type: "bacterial"
elitism: True
mutation_random_sequence: True
# basic [0, 1]
mutation_probability: 0.2
# bacterial
num_of_clones: 1

####### Memetic
memetic: False
lamarck_random_sequence: True
step_size: 0.1
number_of_steps: 1
